version: '3'

networks:
  microservices:
    driver: bridge

volumes:
  nginx:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './frontend/'

  game3d:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './volumes/game3d/'

services:
  nginx:
    container_name: nginx
    networks:
    - microservices
    build: nginx
    image: nginx
    ports:
      - "8080:80"
    restart: on-failure

  user:
    container_name: user
    networks:
    - microservices
    build: backend/user
    image: user
    expose :
    - "8080"
    restart: on-failure

  token:
    container_name: token
    networks:
      - microservices
    build: backend/token
    image: token
    expose :
      - "8080"
    restart: on-failure

  game3d:
    container_name: game3d
    networks:
      - microservices
    build: backend/game3d
    image: game3d
    expose :
      - "8080"
    restart: on-failure
