version: '3'

networks:
  microservices:
    driver: bridge

volumes:
  nginx:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '../site/'

services:
  nginx:
    container_name: nginx
    volumes:
      - nginx:/usr/share/nginx/html
    networks: 
    - microservices
    build: nginx
    image: nginx
    ports: 
      - "8080:80"
    restart: on-failure
  
  djangoTemplate:
    container_name: djangotemplate
    networks: 
    - microservices
    build: backend/djangotemplate
    image: djangotemplate
    expose :
    - "8080"
    restart: on-failure
